/****** Object:  Database [MyRestfullApp]    Script Date: 09/16/2018 22:52:38 ******/
CREATE DATABASE [MyRestfullApp] ON  PRIMARY 
( NAME = N'MyRestfullApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\MyRestfullApp.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyRestfullApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\MyRestfullApp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyRestfullApp] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyRestfullApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyRestfullApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyRestfullApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyRestfullApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyRestfullApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyRestfullApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyRestfullApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyRestfullApp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MyRestfullApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyRestfullApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyRestfullApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyRestfullApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyRestfullApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyRestfullApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyRestfullApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyRestfullApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyRestfullApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyRestfullApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyRestfullApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyRestfullApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyRestfullApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyRestfullApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyRestfullApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyRestfullApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyRestfullApp] SET  READ_WRITE 
GO

ALTER DATABASE [MyRestfullApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyRestfullApp] SET  MULTI_USER 
GO

ALTER DATABASE [MyRestfullApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyRestfullApp] SET DB_CHAINING OFF 
GO


